name: TypeWhisper
options:
  deploymentTarget:
    iOS: "18.0"
  groupSortPosition: top
  generateEmptyDirectories: true
  developmentLanguage: en

settings:
  DEVELOPMENT_TEAM: 2D8ALY3LCL
  CODE_SIGN_STYLE: Automatic
  SWIFT_VERSION: "6.0"
  SWIFT_STRICT_CONCURRENCY: complete

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    majorVersion: 0.9.0

targets:
  TypeWhisper:
    type: application
    platform: iOS
    sources:
      - path: TypeWhisper
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.typewhisper.ios
        INFOPLIST_FILE: TypeWhisper/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
    dependencies:
      - package: WhisperKit

schemes:
  TypeWhisper:
    build:
      targets:
        TypeWhisper: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
